### ISSUE TITLE
Guide preventing Craft Commerce email templates from loading.

### ISSUE THREAD

**Issue by turnstylerj** [wbrowar/craft-guide#103]
## Description

On a site with Craft Commerce, Guide is preventing order confirmation email templates from being displayed. Disabling Guide results in the template being displayed as expected.

## Steps to reproduce
1. Install Craft Commerce and Guide plugins
2. In Commerce, go to System Settings > Emails and create a new email with a "HTML Email Template Path" specified in your templates directory
3. Create a template with the following HTML:
```
<html>
	<body></body>
</html>
```

### Expected behavior
Empty HTML template is displayed on page

### Actual behavior
Page displays error: `Unable to find the template “guide/_partials/admin_globals”.`

## Versions
Craft CMS: 5.2.6
Craft Commerce: 5.0.12
Guide: 4.0.0-beta.1

**Comment by wbrowar** [comment]
Thanks, @turnstylerj, I'll take a look to see if I can figure out why you're getting that error.

**Comment by wbrowar** [comment]
@turnstylerj, I figured out what's going on here and will have a fix for this in the next release (which will be the `4.0.0` non-beta release).

**Comment by wbrowar** [comment]
@turnstylerj, I've just tagged the release for `4.0.0` which resolves this issue.
