### ISSUE TITLE
Javascript error in element index view mode

### ISSUE THREAD

**Issue by rgauthier4c4** [wbrowar/craft-guide#111]
### Description
In one the latest Craft update, some javascript errors have broken the Element index view mode for a Matrix block. The table is not able to load his content. 

At first I thought it was a CraftCms problem, but it is working when I deactivate the Guide plugin.

My staging environment is working fine on the version 5.4.6 of CraftCms, but it is broken on 5.4.9.

I'm on version 5.1.1 of the guide plugin.

### Steps to reproduce

1.  Create a matrix field with Element Index as the view mode.
2. Associated the section with this field
3. Open the section and see the javascript errors

### Expected behavior

![Image](https://github.com/user-attachments/assets/4afb3682-ff31-42e6-aa57-00a6aa38a072)

### Actual behavior

![Image](https://github.com/user-attachments/assets/7e740659-620f-4eef-b04c-61009737e720)

### Craft CMS version

5.4.9

### PHP version

8.2

**Comment by wbrowar** [comment]
Hi @rgauthier4c4, thanks for all of the details and the screenshots of the errors! I'll take a look to see if I can recreate this and then go from there.

Just a couple of questions first.

Did you have any guides that you expected to be on this page (either from being added to the Entries or Control Panel Pages section)?

Do you have any guides that have JavaScript in them, either by using the Twig `{% js %}` tag, or by using the JavaScript editor field in Guide?

I'll still look into it ASAP, but these questions might help narrow it down.

**Comment by rgauthier4c4** [comment]
@wbrowar 

I have a guide that is linked to all entries pages.

 And the guide is simply a twig file with some text, images and a {% css %} tag to add some margin.

**Comment by wbrowar** [comment]
Hi @rgauthier4c4, I tried to match your setup to re-create this and I haven't had luck yet. Just to show you what I did here's a guide I made:

<img width="1728" alt="Screenshot 2024-10-31 at 9 29 21 PM" src="https://github.com/user-attachments/assets/e257504a-7805-4196-a586-ebe3d749c5fb">

I put that on all Entries in the Guide Organizer and tried putting it in the slideout or above the edit fields. I created a Matrix field, added a basic text entry type and one of my entry types that could be a page, and set that to use the Element Index view mode.

<img width="1728" alt="Screenshot 2024-10-31 at 9 29 08 PM" src="https://github.com/user-attachments/assets/03b13ceb-b399-4e05-8879-66a44d8f91e0">

It seems to render fine at the moment, so I'm wondering if there's a setting that I can change to trigger it. I have a couple of ideas for ways we can troubleshoot this:

1. Try clearing out Control Panel Resources (via Utilities > Caches).
2. Can you share the list of other plugins you're using? I see a few in your sidebar, but I don't think any of those should cause any issue (except maybe Unsplash, but that's just a guess).
3. If you’re comfortable doing so, share screenshots of the field settings for your matrix field and maybe the associated entry types. If you want to put that in a reply here that would be okay, or feel free to send it via my email below.
4. If you don't mind sharing the guide that is on that page, go to Utilities > Guide Export + Import, select the guide on the Entries page, copy the JSON and send it to me (again reply here or send an email if you prefer).

Here's my email if you would like to send me any of the info above: will+hello@wbrowar.com

I'll keep trying to debug it on my end, too.

**Comment by rgauthier4c4** [comment]
@wbrowar I've finally found the problem while digging further. In the twig template of my guide, there was a header with a "tabs" id. 

`<h2 id="tabs-guide">Tabs</h2>`

Looks like it was conflicting with the Craftcms javascript of the Element Index view mode.

**Comment by wbrowar** [comment]
Ah. Glad you found out what it was!
