### ISSUE TITLE
With devmode off can't create or edit guides due to twig error

### ISSUE THREAD

**Issue by kylecotter** [wbrowar/craft-guide#13]
Hey Will,

Digging the new features so far!

Getting the following log if devmode is off which breaks editing and adding guides.

`Twig\Error\SyntaxError: Unknown "dump" function. in /var/www/vendor/wbrowar/guide/src/templates/edit.twig`

Thanks!

**Comment by wbrowar** [comment]
Yeah, I just caught that last night, too... I'll have a fix for it in the next release.

**Comment by wbrowar** [comment]
Fixed in version 2.0.1
