### ISSUE TITLE
Import Guide Template Checkbox Options Share IDs

### ISSUE THREAD

**Issue by kylecotter** [wbrowar/craft-guide#14]
![Screen Shot on 2019-07-25 at 01-28-28](https://user-images.githubusercontent.com/505894/61848295-a3925f00-ae7b-11e9-8a58-002f2a44fc19.png)

These checkboxes share the same IDs between both columns so clicking the label on the right column will select the checkbox in the left column.

**Comment by wbrowar** [comment]
Ah, thanks! I'll fix that in the next release, too.

**Comment by wbrowar** [comment]
Fixed in version 2.0.1
