### ISSUE TITLE
[FR] Modal/Button Support on Entry Listing Pages 

### ISSUE THREAD

**Issue by kylecotter** [wbrowar/craft-guide#15]
We've used Structures in some unique ways - ways that we prefer to give editors context to before clicking into an entry.

We've sometimes provided notes and previews of how a section functions on the entry listing page, e.g here:

<img width="1239" alt="Screen_Shot_2019-07-25_at_1_41_40_AM" src="https://user-images.githubusercontent.com/505894/61848931-a2fac800-ae7d-11e9-8f5e-a6daf3d51103.png">

If Guide supported a modal function on these pages by adding a button, perhaps in the top bar, as it does on the individual entry pages that'd be great!

**Comment by wbrowar** [comment]
Great idea. I can see this being helpful on asset volume pages, too. Thanks for the suggestion!

**Comment by wbrowar** [comment]
So... @kylecotter, it took a while to get here, but you can totally do this with Guide 3! Actually a lot of the new CSS selector setup was initiated to resolve this. It’ll be out tomorrow, but you can try this out now on the `3.x-dev` version.

**Comment by KatieMFritz** [comment]
@wbrowar Could you provide an example of how to do this? I would also love to include guides at the index view for entries and assets but haven't worked out how yet.
