### ISSUE TITLE
Guide iframe CSS affects live preview

### ISSUE THREAD

**Issue by kylecotter** [wbrowar/craft-guide#16]
I _think_ the Guide CSS is affecting live preview due to it's global iframe css. Specifically having iframe set to `position: absolute;` globally forces the live preview window to narrow considerably. 
<img width="1680" alt="Screen_Shot_2019-07-26_at_1_37_19_PM" src="https://user-images.githubusercontent.com/505894/61970356-9f189400-afaa-11e9-8ea3-8413fc006b35.png">

**Comment by wbrowar** [comment]
Fixed in version 2.0.1
