### ISSUE TITLE
[FR] Reuse Guides

### ISSUE THREAD

**Issue by kylecotter** [wbrowar/craft-guide#18]
Maybe I'm doing this wrong, but I don't see a way to have a Guide in multiple contexts within the organizer. Ideally we'd have a generic guide that applies to multiple channels and want that to be a modal for each. Or, we'd want a Guide to show up as a modal, along with show up in our master guide. Guidance on how to do that currently, or is that an enhancement? Thanks, Will!

**Comment by wbrowar** [comment]
This is on my list to address. I have variables to get guide content (like `{{ craft.guide.getAll(OBJECT) }}`), but to render it out properly and easily needs something like an include variable.

Maybe something like `{{ craft.guide.include({ slug: 'assets' } ) }}`. This would find the guide and run in through Guide’s render partial that gets it into the correct format.

This way you could have a bunch of partial guides sitting in Unused Guides and just include them around and mix and match as needed.

**Comment by kylecotter** [comment]
Yeah, I can get behind that!

**Comment by wbrowar** [comment]
Okay, I added this and created a Twig component. Thanks again for the suggestion!

I'll take a look at the other FRs here for a future release since they will both take a little more time to complete.

Thanks again!
Will

**Comment by wbrowar** [comment]
Added in version 2.0.1
