### ISSUE TITLE
Suggestion - Remove the rotation on guide/welcome

### ISSUE THREAD

**Issue by darylknight** [wbrowar/craft-guide#21]
Congrats on a beautiful introduction to a plugin! I really like the slide-in animation of the welcome book and the setup section. Only a minor thing I thought I'd point out is that browser rendering often isn't great for angles, and this transform for the book makes the text look a bit fuzzy. Totally up to you, but thought I'd highlight it at least on Chrome, OSX:

![image](https://user-images.githubusercontent.com/1250017/63838122-6d1d9780-c985-11e9-8fb4-92ce4693e13c.png)

**Comment by wbrowar** [comment]
It looks like Chrome has fixed this by improving the rendering on rotated elements. If you still see this issue, please let me know.

**Comment by darylknight** [comment]
Yep, you're right - looks a lot better than it used to.

Only other thing is something that can't be changed - I'm sure your'e aware of it!

![image](https://user-images.githubusercontent.com/1250017/78355440-5b087500-75b6-11ea-8dfb-f5516b230e14.png)
