### ISSUE TITLE
Suggestion - Multiple instances

### ISSUE THREAD

**Issue by JeanLucEsser** [wbrowar/craft-guide#23]
Great plugin, very helpful, but unless I'm mistaken, there's one obvious thing missing after a few minutes of using the plugin: being able to assign a guide to multiple places.

I have some general guides about "generic principles" that I'd like to have on different sections edit pages, and the only way I can find of doing this is by cloning the guide, which defeats the purpose. It would be really nice to have multiple instances of a single guide so we can show it and access it from different places.

Did I miss something?

Replacing "Unused Guides" by "Available Guides" would do the trick.

-- JL

**Comment by wbrowar** [comment]
Hi @JeanLucEsser, I'm glad you’re liking the plugin so far!

The way that I've tried to solve this is to have a workflow like this:

1. Create a Guide (for example, say the slug of the guide is 'assets') and either put that in the Guide CP or leave it in "Unused Guides"
1. Create your guide for your first edit page and include the contents of the first guide by using this: `craft.guide.include({ slug: 'assets' })`
1. Save that and then clone it for your other edit pages.

In this case, you’ll only have one place to edit the guide and then that content will be distributed out to all of the other instances.

In retrospect, I wish I thought of the idea of guide instances or maybe even letting you set some of these things within the guides themselves, but the `include()` method came up after I had launched Guide 2.. Anyway, I hope this works for you for now.

I really do like the label "Available Guides" better than "Unused Guides". Even if it functioned the same, it might be good to update it.

Will

**Comment by JeanLucEsser** [comment]
Hi @wbrowar !

Yes, that works great. It makes as many guides (and as many slugs) as there clones, but that's not a real issue, nobody actually cares. So it works nicely and it has one nicety as you can name the clones differently depending on where you want them to appear (and even have a specific intro).

Maybe I missed it in the docs but it's worth emphasizing I think.

Great work.
