### ISSUE TITLE
craft_guide_organizers doesn't exist

### ISSUE THREAD

**Issue by raptureaid** [wbrowar/craft-guide#24]
After updating from `1.4.0` to any `2.0.0+` version of the guide, the following error message is returned:

```
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'craft3_20191021.craft_guide_organizers' doesn't exist
The SQL being executed was: SELECT *
FROM `craft_guide_organizers`
```

**Comment by wbrowar** [comment]
Hi @raptureaid I have to figure out these bugs, but in the mean time, a workaround seems to be if you run the migration via the command line it should work. I'll update this when the migration bug is fixed.
