### ISSUE TITLE
Only one guide can be dragged from Unused Guides to Guide CP

### ISSUE THREAD

**Issue by tyssen** [wbrowar/craft-guide#25]
After installing the plugin and importing the data and templates and ending up on the Organizer page, there's a box, Unused Guides, with four guides on the left and a box on the right, Guide CP, to drag guides to.

I can only drag one guide across to Guide CP. Is that because I'm using the free version of the plugin, or should I be able to add all four?

**Comment by wbrowar** [comment]
Hey @tyssen, you should be able to drag all 4 over. There's no limit to the amount of guides you can move over into the Guide CP section. It looks like the drag-and-drop target changes once you've moved one guide over, so I'll take a look and see if I can make that a little more user-friendly.

Thanks for bringing this up and I'll keep you updated.

**Comment by tyssen** [comment]
Great, thanks.


On 16 December 2019 at 7:37:09 am, Will Browar (notifications@github.com) wrote:

Hey @tyssen, you should be able to drag all 4 over. There's no limit to the amount of guides you can move over into the Guide CP section. It looks like the drag-and-drop target changes once you've moved one guide over, so I'll take a look and see if I can make that a little more user-friendly.

Thanks for bringing this up and I'll keep you updated.

**Comment by wbrowar** [comment]
Hey John, I added drop targets to the next update of Guide so it’ll be easier to drag-and-drop within the Organizer. It'll be out around the Craft 3.4 release.

<img width="1180" alt="Screen Shot 2019-12-15 at 9 04 23 PM" src="https://user-images.githubusercontent.com/2158662/70874060-82dbba80-1f7e-11ea-84ec-d179f322431d.png">
