### ISSUE TITLE
BUG: When assets are missing - almost impossible to login to CP

### ISSUE THREAD

**Issue by michtio** [wbrowar/craft-guide#28]
I've noticed this when dealing with asset mismatches, so tried to rebuild the asset tree, and didn't add the guide assets in yet.

What happens is that the login in the CP times out. "Can't find img x" from the ones that are needed for the guide.

There should be a fallback for this, if the images aren't found some kind of placeholder is shown in place...

**Comment by wbrowar** [comment]
Hey Michael, I'll take a look and see if something’s going on with the images hanging up the login.

As far as the fallback goes, I was thinking of only showing that to `admin` users so it doesn't look like an error other users. What do you think of that?

**Comment by wbrowar** [comment]
Oh, are you running into the login error due to an image that's was supposed to be on a Dashboard widget or some other location in the CP? Also, was the error occurring in a Markdown or Twig-based template?

Thanks,
Will

**Comment by michtio** [comment]
@wbrowar exactly, the asset is missing that is supposed to be on a dashboard widget, it is a markdown based template.

I think the easiest solution for this is that Guide comes with some grey with a broken image inside kind of fallback image, and a check happens if asset exists display if not, display the placeholder?

**Comment by michtio** [comment]
@wbrowar for your suggestion, that seems okay, but as long as non-admin users can login and don't run into that error seems fine. 

Personally I don't mind users getting a placeholder in place without the image showing, CP users can always file an issue themselves if they encounter something like that. Just in case the devs are the only admins on the platform, we won't be logging in at all times of course.
