### ISSUE TITLE
New Page Template Guides are not displayed on Windows

### ISSUE THREAD

**Issue by wsydney76** [wbrowar/craft-guide#29]
Evaluating the plugin on a Windows 10 system, there is a `This guide seems to have moved.` error when trying to display a new guide (page template).

Looks like a full path like `E:\craft\temp1\templates/_guide\award.twig` is stored in the db table instead of just `award.twig`

Obviously in https://github.com/wbrowar/craft-guide/blob/82e155fa813eda52485def55ba9e96c2d3cfcac2/src/Guide.php#L467 `'/'` is used instead of `DIRECTORY_SEPARATOR`

Replacing that fixes the error.

Thanks
/Mel

**Comment by wbrowar** [comment]
Thanks, @wsydney76! This will be fixed in the next release of Guide.
