### ISSUE TITLE
Can't create guides or see existing guides

### ISSUE THREAD

**Issue by jedimonkey** [wbrowar/craft-guide#31]
I've ran through the steps and imported from github the templates/assets/guides, however nothing appears to show in the organizer. I've also tried creating a guide and using an existing template and it doesn't appear to error but nothing is showing up in the organizer. I can see the database records getting created in the `guide_guides` table and there is a record in the guide_organizers table, however the organizer view just shows that there is nothing in the Available Guides.

![image](https://user-images.githubusercontent.com/5734286/88021242-bce9ec00-cb5f-11ea-8b02-ddf10ad8c734.png)

I'm at a loss on what to fix, as it doesn't appear to be generating any warnings/errors (confirmed in the logs) and I can see that the organizer node has json in its organizer-config property. So it looks like all the bits are working and the json is valid, but it's failing somewhere to show me any guides. And trying to debug the minified js is a bit too hard (without access to the original js).

Any help would be appreciated.

**Comment by wbrowar** [comment]
Hey Marcus, could you please share your PHP and MySQL versions and versions of Craft and Guide? I'll see if I can re-create it with your setup.

**Comment by jedimonkey** [comment]
Hey @wbrowar,

Thanks for the quick response, I'll see if I can whip up a clean site to test with as there is a lot of code otherwise. It's running latest craft (3.4.28.1) with postgresql. Will come back to you asap.

thanks!

**Comment by jedimonkey** [comment]
Hi @wbrowar,

Found the issue - we are using Postgres so when you mentioned mysql I was thought that may be the issue. I noticed that the JSON getting generated had whitespace on a bunch of the fields. Turns out that the schema is using char() rather than a varchar (or string in yii schema terminology). I'll quickly create a PR for you to amend this to a string. Probably not worth making a migration for existing users, as if it's working under mysql, then no point forcing them to change.

**Comment by jedimonkey** [comment]
I've tested this with both MySQL (5.7) and Postgresl (12).

**Comment by wbrowar** [comment]
Ah, when you mentioned Postgres I wondered about that. I'll take a look at the PR and plan to merge it in. Thanks for troubleshooting that.

I was prepping a release for some minor things for 3.5 compatibility. I could roll this into that release that will be out when 3.5 hits or I'd be happy to do a release for this PR if you don't plan on upgrading to 3.5 right away. Please just let me know either way.

**Comment by jedimonkey** [comment]
If you don't mind doing a release sooner than later that would be awesome, the team want to get to work setting up some docs for a project. We should be buying a license tomorrow for the plugin 👍

**Comment by wbrowar** [comment]
Absolutely. Thanks again for figuring out what went wrong. The 2.1.5 release is live and there will be another release ready for Craft 3.5 whenever that is released.
