### ISSUE TITLE
Fix Composer 2 compatibility

### ISSUE THREAD

**Issue by brandonkelly** [wbrowar/craft-guide#34]
When installing this plugin with Composer 1, the following deprecation notice is output:

> Deprecation Notice: Class `wbrowar\guide\assetbundles\Guide\GuideAsset` located in `./vendor/wbrowar/guide/src/assetbundles/guide/GuideAsset.php` does not comply with psr-4 autoloading standard\. It will not autoload anymore in Composer v2\.0\.

Composer 2 was released on October 24, and is now the default version that will be installed, so it’s critical that this gets resolved ASAP, or people will start getting `Class not found` errors.

To fix, run the following command:

```bash
> git mv src/assetbundles/guide src/assetbundles/Guide
```

Then commit your change and [tag a new release](https://craftcms.com/docs/3.x/extend/plugin-store.html#plugin-releases).

_(Note that you must use the `git mv` command, as Git tends to not notice case-sensitive file renames otherwise.)_

**Comment by wbrowar** [comment]
Thanks, @brandonkelly! Tagged in 2.2.1

**Comment by brandonkelly** [comment]
Thanks!
