### ISSUE TITLE
docs page share image is nuxt content's

### ISSUE THREAD

**Issue by olets** [wbrowar/craft-guide#51]
The documentation site's preview image is not what I'd expect.

### Details

https://guide.wbrowar.com/'s `og:image`

```
<meta data-n-head="ssr" data-hid="og:image" property="og:image" content="https://guide.wbrowar.com/preview.png">
```

points to

https://guide.wbrowar.com/preview.png

which is

![preview](https://user-images.githubusercontent.com/3282350/142920730-d9132e56-95ab-4ff2-b583-6cb7b6187133.png)

Example result: sharing on Slack:

![image](https://user-images.githubusercontent.com/3282350/142920526-e108b4de-9155-4aff-bc95-52928473b975.png)

**Comment by wbrowar** [comment]
Ah, thanks, @olets! I’ll fix this in the next release.

**Comment by wbrowar** [comment]
Thanks, again! This has been updated in [3.1.1](https://github.com/wbrowar/craft-guide/releases/tag/3.1.1)
