### ISSUE TITLE
CraftCMS 4 Support

### ISSUE THREAD

**Issue by davidhellmann** [wbrowar/craft-guide#70]
Is it planned to support CraftCMS 4 and is there a Timeline?

**Comment by wbrowar** [comment]
Hey @davidhellmann! Yes, Guide will get updated for Craft 4 (along with [Little Layout](https://github.com/wbrowar/craft-little-layout)). I'm working on the upgrades now and I hope to have them all set maybe a week before Craft 4 launches. At the very least I plan on having it ready for the May 4 Craft 4 launch.

**Comment by wbrowar** [comment]
@davidhellmann good news! Progress on the Craft 4 version is coming along nicely and I'm just about to do a thorough test of all of it's features. At this point I plan on launching with the same features in the Craft 3 version, so this update is all about compatibility with Craft 4.

If you'd like to try out the latest version, set the version in your `composer.json` file to `dev-3.x-craft-4`. If you notice anything out of order, please let me know!

**Comment by wbrowar** [comment]
Guide 3.2.0 will be released today with support for Craft 4!
