### ISSUE TITLE
Error on widget

### ISSUE THREAD

**Issue by gglnx** [wbrowar/craft-guide#82]
Currently the dashboard pages doesn't load for users with the Guide widget. We get the following exception:

```
yii\base\ErrorException: Attempt to read property "content" on null in /vendor/wbrowar/guide/src/services/Guide.php:79
Stack trace:
#0 /vendor/craftcms/cms/src/web/ErrorHandler.php(84): yii\base\ErrorHandler->handleError()
#1 /vendor/wbrowar/guide/src/services/Guide.php(79): craft\web\ErrorHandler->handleError()
#2 /vendor/wbrowar/guide/src/widgets/Guide.php(145): wbrowar\guide\services\Guide->getGuides()
#3 /vendor/wbrowar/guide/src/widgets/Guide.php(132): wbrowar\guide\widgets\Guide->_getGuideFromGuideId()
#4 /vendor/craftcms/cms/src/controllers/DashboardController.php(511): wbrowar\guide\widgets\Guide->getBodyHtml()
#5 /vendor/craftcms/cms/src/controllers/DashboardController.php(105): craft\controllers\DashboardController->_getWidgetInfo()
#6 [internal function]: craft\controllers\DashboardController->actionIndex()
#7 /vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#8 /vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#9 /vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction()
#10 /vendor/craftcms/cms/src/web/Application.php(293): yii\base\Module->runAction()
#11 /vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction()
#12 /vendor/craftcms/cms/src/web/Application.php(278): yii\web\Application->handleRequest()
#13 /vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest()
#14 /web/index.php(14): yii\base\Application->run()
#15 {main}
```

**Comment by gixxy22** [comment]
same issue with me. couldnt see where to populate "content" so had to uninstall.

Craft Pro 3.7.51

**Comment by robinsm** [comment]
I also have the same problem. Craft 3.7.47.1

**Comment by robinsm** [comment]
I was able to get around this by commenting out line 79 of /vendor/wbrowar/guide/src/services/Guide.php

The dashboard then loaded and using the settings icon top right of the dashboard, I was able to remove the widget that was causing the issue by pointing to a deleted Guide.  Hope that helps fix the issue.

**Comment by gixxy22** [comment]
> I was able to get around this by temporarily commenting out line 79 of /vendor/wbrowar/guide/src/services/Guide.php
> 
> The dashboard then loaded and using the settings icon top right of the dashboard, I was able to remove the widget that was causing the issue by pointing to a deleted Guide. Hope that helps fix the issue.

excellent, can confirm this works as a temporary workaround, hopefully there will be a fix soon, thanks for updating us!

**Comment by wbrowar** [comment]
Hi everyone, sorry for the delay here and thanks for your patience! I was out of town for the past couple of weeks.

@robinsm thanks for pointing out the issue here. I've put in a sanity check that should fix this issue. 

For the Craft 3 version of guide, you can update to Guide 3.1.2:
```
"wbrowar/guide": "^3.1.2",
```

And for the Craft 4 version of guide, you can use Guide 3.2.1:
```
"wbrowar/guide": "^3.2.1",
```

If for some reason you notice this issue again please let me know.

**Comment by robinsm** [comment]
Thanks for the update and the fix @wbrowar , will let you know if we see any issues after the next update.
